#!/bin/bash

# Link dotfiles
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf

# Install packages
sudo apt-get install -y fzf
sudo apt-get install -y ripgrep

if [ $SPIN ]; then
	echo “This only runs on spin!”
fi
